services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=dev-secret
      - MLFLOW_RUN_ID=${MLFLOW_RUN_ID}
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
